import type { NextConfig } from "next";

const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? '';

// Traefik (Coolify) strips the path prefix before forwarding to Next.js,
// so we only set assetPrefix so client-side URLs include the prefix.
// Puppeteer hits Next.js directly on localhost (no Traefik), so we need
// rewrites to accept the prefixed URLs generated by assetPrefix.
const nextConfig: NextConfig = {
  assetPrefix: basePath || undefined,
  async rewrites() {
    if (!basePath) return [];
    return [
      { source: `${basePath}/_next/:path*`, destination: '/_next/:path*' },
      { source: `${basePath}/images/:path*`, destination: '/images/:path*' },
      { source: `${basePath}/fonts/:path*`,  destination: '/fonts/:path*'  },
      { source: `${basePath}/api/:path*`,    destination: '/api/:path*'    },
      { source: `${basePath}/print/:path*`,  destination: '/print/:path*'  },
      { source: basePath,                    destination: '/'              },
    ];
  },
};

export default nextConfig;
